// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"clsld.com/test-wire/data"
)

// Injectors from wire.go:

func InitializeBroadCast() data.BroadCast {
	message := data.NewMessage()
	channel := data.NewChannel(message)
	broadCast := data.NewBroadCast(channel)
	return broadCast
}
